name: ci para teste da api

on:
  pull_request:
    branches:
      - "main"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Implementar java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Buscar banco de dados
        run: docker compose up -d db --wait

      - name: Rodar testes
        run: mvn clean package
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/rateio_api_db
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root

      - name: Compose down
        run: docker compose down